# Generated by cucumber-sinatra. (2013-12-03 12:11:29 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/metrics-api.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MetricsApi

class MetricsApiWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MetricsApiWorld.new
end
