source 'https://rubygems.org'

ruby "2.4.1"

gem 'rake'
gem 'sinatra'
gem 'grape'
gem 'grape-entity'
gem 'grape-swagger'
gem 'grape-swagger-entity'
gem 'github-pages'
gem 'jekyll'
gem 'github-markup'
gem 'commonmarker'
gem 'dotenv'
gem 'thin'
gem 'haml'
gem 'foreman'
gem 'mongoid'
gem 'rack-conneg'
gem 'rack-cors', :require => 'rack/cors'
gem 'iso8601'
gem 'compass'
gem 'bootstrap-sass'
gem 'pusher'
gem 'actionview'
gem 'byebug'

group :test do
  gem 'capybara-webkit'
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'rspec'
  gem 'rack-test'
  gem 'byebug'
  gem 'launchy'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-jasmine'
  gem 'guard-cucumber'
  gem 'terminal-notifier-guard'
  gem 'coveralls', require: false
  gem 'cucumber-api-steps', require: false, git: 'https://github.com/theodi/cucumber-api-steps.git', branch: 'feature-test-content-type'
  gem 'database_cleaner'
  gem 'guard-shotgun'
  gem 'jasmine'
  gem 'timecop'
  gem 'data_kitten'
  gem 'linkeddata', '< 3.0' #pinned for datakitten compatibility
  gem 'webmock'
end
